name: SSH into VPS and deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy over SSH

    steps:
      - name: Debug secrets
        run: |
          echo "HOST=${{ secrets.SSH_HOST }}"
          echo "PORT=${{ secrets.SSH_PORT }}"
          echo "USER=${{ secrets.SSH_USERNAME }}"

      - name: Deploy project over SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p opensource-usefull

            if [ ! -d opensource-usefull/rssskull/.git ]; then
              git clone https://github.com/fazil-syed/rssskull.git opensource-usefull/rssskull
            fi

            cd opensource-usefull/rssskull
            git pull --rebase -Xours 

            docker compose up -d --build
